server:
  port: 8081
spring:
  kafka:
    bootstrap-servers:
      - http://localhost:9092
    template:
      default-topic: tacocloud.orders.topic
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: tacocloud-kitchen
      properties:
        spring.json.trusted.packages: com.example.tacocloud.domain.TacoOrder
